# Numpy
1 ndarray 的特性：
- 1. ndarray 的元素必须相同
- 2. ndarray 的元素必须为同一种数据类型
- 3. ndarray 的元素必须为同一维数


## 创建1

In [1]:
import numpy as np

In [ ]:
arr = np.array(2) #创建0维数组
print(arr)
print('arr的维度:',arr.ndim)

In [ ]:
#预定义形状:全0
arr = np.zeros((2,5),dtype=int)
print(arr)

In [ ]:
#预定义形状
arr1 = np.zeros((3,),dtype=int)
arr2 = np.empty((3,2))
print(arr1)
print(arr2)

In [ ]:
#指定
arr = np.full((2,3), 1)
print(arr)

## 创建2

In [ ]:
#等差数列
arr = np.arange(0, 10, 1) #start, end, step
print(arr)

In [ ]:
#等间隔序列
arr = np.linspace(0, 8, 3)
print(arr)

In [ ]:
#对数间隔序列
arr = np.logspace(0, 8, 3, base=2) #2的0次方到8次方，间隔为2的3次方
print(arr)

## 创建-特殊矩阵

In [ ]:
#单位矩阵
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#对角矩阵
arr = np.diag([1,2,3])  #主对角线元素
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [6]:
#生成随机数列（正态分布）
arr = np.random.randn(2, 3)
print(arr)

[[ 1.27633313 -0.86443708  0.40375217]
 [ 0.415732   -0.74342642  0.68063725]]


In [12]:
#设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, size=(2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


In [ ]:
"""
某城市一周最高气温为[28,30,29,31,32,30,29]。
-计算平均气温,最高气温和最低气温。
-找出气温超过30度的天数。
"""

In [11]:
import numpy as np
temp = np.array([28,30,29,31,32,30,29])
avg_temp = np.mean(temp)
print(f'平均气温：{avg_temp:.3f}')
print(f'最高气温：{np.max(temp):.3f}')
print(f'最低气温：{np.min(temp):.3f}')

print(len(temp[temp>30]))
print(np.sum(temp>30))
print(np.count_nonzero(temp>30))
print(np.where(temp>30, temp , 0))
print(np.cumsum(np.where(temp>30, 1 , 0))[-1])

平均气温：29.857
最高气温：32.000
最低气温：28.000
2
2
2
[ 0  0  0 31 32  0  0]
2


In [18]:
'''A=[[1,2],[3,4]]和B=[[5,6],[7,8]]
计算A+B, A*B,矩阵乘法
'''
A=np.array([[1,2,2],[3,4,1],[3,4,2]])
B=np.array([[5,6,1],[7,8,4],[3,4,4]])
#print(A+B)
#print(A*B)
#print(A@B)
C=np.dot(A,B)
print(C)

C[C%2==0]=1
print(C)

[[25 30 17]
 [46 54 23]
 [49 58 27]]
[[25  1 17]
 [ 1  1 23]
 [49  1 27]]


In [ ]:
arr = np.arange(1,13)
arr = arr.reshape(3,4)
print(arr)

print('每行和',arr.sum(axis=1))
print('每列和',arr.sum(axis=0))
print('每行平均值',arr.mean(axis=1))
print('每列平均值',arr.mean(axis=0))
arr = arr.reshape(12)
arr = np.reshape(arr,12)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行和 [10 26 42]
每列和 [15 18 21 24]
每行平均值 [ 2.5  6.5 10.5]
每列平均值 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Series

In [5]:
import pandas as pd
s = pd.Series([1, 2, 3, 4, 5])
print(s)
#自定义索引
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s)
#自定义name
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'], name='num')
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: num, dtype: int64


In [4]:
#通过字典创建
s = pd.Series({'a': 1, 'b': 2, 'c': 3})
print(s)

s1 = pd.Series(s, index=['b', 'c', 'd'])
print(s1)

a    1
b    2
c    3
dtype: int64
b    2.0
c    3.0
d    NaN
dtype: float64


In [13]:
print(s.shape)
print(s.dtype)
print(s.size)
print(s.nbytes)
print(s.ndim)
print(s.flags, s.name, s.values)
print(s.loc['a'])#获取索引显示
print(s.iloc[0])#获取索引隐式

(5,)
int64
5
40
1
<Flags(allows_duplicate_labels=True)> num [1 2 3 4 5]
1
1


In [17]:
print(s['a'])

1


In [ ]:
#s.head()

#s.isin([1])
s.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
Name: num, dtype: float64

In [11]:
import pandas as pd
import numpy as np
np.random.seed(42)
values = np.random.randint(50, 101 , 10)
index = []
for i in range(10):
    index.append('No.'+str(i+1))
score = pd.Series(values, index=index, name='score')
score.describe()
#高于平均分的人数
print('高于平均分的人数:',score[score>score.mean()].count())

高于平均分的人数: 4


# DataFrame

In [25]:
import pandas as pd
import numpy as np
#1.通过Series创建
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([5,6,7,8,9])
#df = pd.DataFrame({'第一列':s1,'two':s2})

#2.通过字典创建
#df = pd.DataFrame({'第一列':[1,2,3,4,5],'two':[5,6,7,8,9]})
#3.通过创建


In [ ]:
import pandas as pd
#df = pd.read_csv('C:\Users\Windy\Documents\Code\Python\weather_data.csv')
df = pd.read_csv('..\\..\\weather_data.csv')
df

,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,date,frost_day,heat_day,severe_heat_day,dry_day,dry_streak,strong_wind_day,dust_storm_risk,rainy_day,continuous_rain_streak
0,33.5,21.2,0.1,21.6,23,2025-06-08,False,False,False,True,1,True,True,False,0
1,33.5,20.6,0.0,24.9,23,2025-06-09,False,False,False,True,2,True,True,False,0
2,33.0,17.6,0.0,12.0,23,2025-06-10,False,False,False,True,3,False,False,False,0
3,37.2,19.4,0.0,16.4,20,2025-06-11,False,True,False,True,4,False,True,False,0
4,33.7,22.0,0.0,28.9,23,2025-06-12,False,False,False,True,5,True,True,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,28.0,13.9,0.0,18.7,25,2026-06-04,False,False,False,True,12,True,True,False,0
362,29.7,14.4,0.0,27.0,25,2026-06-05,False,False,False,True,13,True,True,False,0
363,24.4,14.5,0.0,27.2,29,2026-06-06,False,False,False,True,14,True,True,False,0
364,26.0,12.2,0.0,17.2,23,2026-06-07,False,False,False,True,15,True,True,False,0
